=== silnrsi/typetuner/feat_set.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DOCTYPE all_features SYSTEM "feat_all.dtd" --> <!-- put at top of XML file to validate -->

<!ELEMENT features_set (feature+)>
<!ATTLIST features_set
	version CDATA #REQUIRED>
<!ELEMENT feature (value+)>
<!ATTLIST feature
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT value EMPTY>
<!ATTLIST value
	name CDATA #REQUIRED>

=== silnrsi/typetuner/web/packages/Literacy AmArea.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE features_set SYSTEM "feat_set.dtd">
<features_set version="1.0">
	<feature name="Literacy alternates" value="True">
	</feature>
	<feature name="Barred-bowl forms" value="True">
	</feature>
	<feature name="Chinantec tones" value="True">
	</feature>
	<feature name="Uppercase Eng alternates" value="Capital N with tail">
	</feature>
	<feature name="Show deprecated PUA" value="Through Unicode 5.1">
	</feature>
	<feature name="Line spacing" value="Imported">
	</feature>
	<imported_line_metrics font="Chinstd SILCharis" em-sqr="2048" metrics="2034 512 0 2034 512 2034 512 0"/>
</features_set>

=== silnrsi/typetuner/feat_set_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE features_set SYSTEM "feat_set.dtd">
<features_set version="1.1">
	<feature name="Capital Eng alternates" value="Large eng on baseline">
		<value name="Large eng with descender"/>
		<value name="Large eng on baseline"/>
		<value name="Capital N with tail"/>
	</feature>
	<feature name="Literacy alternates" value="True">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Barred-bowl forms" value="True">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Vietnamese-style diacritics" value="False">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Romanian-style diacritics" value="True">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Line spacing" value="Imported">
		<value name="Normal"/>
		<value name="Tight"/>
		<value name="Loose"/>
		<value name="Imported"/>
	</feature>
	<imported_line_metrics font="SIL Doulos" em-sqr="1024" metrics="943 225 0 943 225 943 225 0"/>
</features_set>

=== silnrsi/typetuner/test/feat_set_def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE features_set SYSTEM "feat_set.dtd">
<features_set version="1.0">
	<feature name="Capital Eng alternates" value="Large eng with descender">
		<value name="Large eng with descender"/>
		<value name="Large Eng on baseline"/>
		<value name="Capital N with tail"/>
	</feature>
	<feature name="Literacy alternates" value="False">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Barred-bowl forms" value="False">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Vietnamese-style diacritics" value="False">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Romanian-style diacs" value="False">
		<value name="False"/>
		<value name="True"/>
	</feature>
	<feature name="Line spacing" value="Normal">
		<value name="Normal"/>
		<value name="Tight"/>
		<value name="Loose"/>
		<value name="Imported"/>
	</feature>
</features_set>
